# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Noodle-Bytes. All Rights Reserved

"""
Tests for the HTML coverage report writer. The npm invocations are faked so these
run without node or an installed viewer; what is covered is ReportWriter's own
behaviour (install check, argument passing, failure handling, output copying
and the single-use contract). The report content itself is generated by the
viewer's readableReport module, which has its own vitest coverage.
"""

import json
import subprocess
from pathlib import Path

import pytest

from bucket.rw import ReportWriter

from ..utils import GeneratedReadout


class FakeReportNpm:
    """
    Stand-in for subprocess.call that mimics `npm ls` and `npm run report`.
    The report step parses --json/--output from the args and writes a dummy
    report where ReportWriter expects to find it.
    """

    def __init__(self, ls_result=0, report_result=0):
        self.ls_result = ls_result
        self.report_result = report_result
        self.report_args = []

    def __call__(self, args, cwd=None, **kwargs):
        if args[:2] == ["npm", "ls"]:
            return self.ls_result
        assert args[:4] == ["npm", "run", "report", "--"]
        self.report_args.append(args[4:])
        if self.report_result == 0:
            json_path = Path(args[args.index("--json") + 1])
            assert json_path.exists(), "report must run after the JSON is written"
            output_path = Path(args[args.index("--output") + 1])
            output_path.write_text("<!DOCTYPE html>coverage report\n")
        return self.report_result

    @property
    def last_args(self):
        return self.report_args[-1]


@pytest.fixture
def web_path(tmp_path):
    path = tmp_path / "viewer"
    path.mkdir()
    return path


class TestReportWriter:
    def test_raises_when_viewer_not_installed(self, web_path, monkeypatch):
        monkeypatch.setattr(subprocess, "call", FakeReportNpm(ls_result=1))
        with pytest.raises(RuntimeError, match="Viewer not installed"):
            ReportWriter(web_path, "report.html")

    def test_write_produces_report(self, web_path, tmp_path, monkeypatch):
        fake_npm = FakeReportNpm()
        monkeypatch.setattr(subprocess, "call", fake_npm)
        output = tmp_path / "out" / "report.html"
        output.parent.mkdir()

        writer = ReportWriter(web_path, output)
        writer.write(GeneratedReadout())

        assert output.read_text() == "<!DOCTYPE html>coverage report\n"
        assert len(fake_npm.report_args) == 1

    def test_default_options_pass_only_axis_cap(self, web_path, tmp_path, monkeypatch):
        fake_npm = FakeReportNpm()
        monkeypatch.setattr(subprocess, "call", fake_npm)

        writer = ReportWriter(web_path, tmp_path / "report.html")
        writer.write(GeneratedReadout())

        max_axis_idx = fake_npm.last_args.index("--max-axis-values")
        assert fake_npm.last_args[max_axis_idx + 1] == "64"
        for flag in ["--max-tier", "--tags", "--point"]:
            assert flag not in fake_npm.last_args

    def test_scope_options_map_to_flags(self, web_path, tmp_path, monkeypatch):
        fake_npm = FakeReportNpm()
        monkeypatch.setattr(subprocess, "call", fake_npm)

        writer = ReportWriter(
            web_path,
            tmp_path / "report.html",
            max_axis_values=8,
            max_tier=2,
            tags=["uart", "axi"],
            point="Pets.dogs*",
        )
        writer.write(GeneratedReadout())

        max_axis_idx = fake_npm.last_args.index("--max-axis-values")
        assert fake_npm.last_args[max_axis_idx + 1] == "8"
        max_tier_idx = fake_npm.last_args.index("--max-tier")
        assert fake_npm.last_args[max_tier_idx + 1] == "2"
        tags_idx = fake_npm.last_args.index("--tags")
        assert fake_npm.last_args[tags_idx + 1] == "uart,axi"
        point_idx = fake_npm.last_args.index("--point")
        assert fake_npm.last_args[point_idx + 1] == "Pets.dogs*"

    def test_write_accepts_list_of_readouts(self, web_path, tmp_path, monkeypatch):
        fake_npm = FakeReportNpm()

        json_records = []

        def capture_json(args, cwd=None, **kwargs):
            result = fake_npm(args, cwd=cwd, **kwargs)
            if args[:2] != ["npm", "ls"]:
                json_path = Path(args[args.index("--json") + 1])
                json_records.append(len(json.loads(json_path.read_text())["records"]))
            return result

        monkeypatch.setattr(subprocess, "call", capture_json)
        output = tmp_path / "report.html"

        writer = ReportWriter(web_path, output)
        writer.write([GeneratedReadout(rec_seed=1), GeneratedReadout(rec_seed=2)])

        assert output.exists()
        # Both readouts must land in the one cov.json handed to the script.
        assert json_records == [2]

    def test_writer_is_single_use(self, web_path, tmp_path, monkeypatch):
        monkeypatch.setattr(subprocess, "call", FakeReportNpm())
        writer = ReportWriter(web_path, tmp_path / "report.html")
        writer.write(GeneratedReadout())
        with pytest.raises(RuntimeError, match="new ReportWriter instance"):
            writer.write(GeneratedReadout())

    def test_report_failure_raises(self, web_path, tmp_path, monkeypatch):
        monkeypatch.setattr(subprocess, "call", FakeReportNpm(report_result=1))
        writer = ReportWriter(web_path, tmp_path / "report.html")
        with pytest.raises(RuntimeError, match="Could not generate coverage report"):
            writer.write(GeneratedReadout())
