# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Noodle-Bytes. All Rights Reserved

import shutil
import subprocess
import tempfile
from pathlib import Path

from .common import Readout, Writer
from .json import JSONWriter


class ReportWriter(Writer):
    """
    Write coverage information out to a human-readable standalone HTML report.

    The report itself is generated by the viewer's shared report module
    (viewer/src/services/readableReport.ts) via `npm run report`, so the
    formatting logic is implemented once for both this writer and the
    viewer UI's export action.
    """

    def __init__(
        self,
        web_path: str | Path = Path(__file__).parent.parent.parent / "viewer",
        output: str | Path = "report.html",
        *,
        max_axis_values: int = 64,
        max_tier: int | None = None,
        tags: list[str] | None = None,
        point: str | None = None,
    ):
        self.web_path = Path(web_path)
        self.output = Path(output)
        self.written = False

        self.report_args: list[str] = ["--max-axis-values", str(max_axis_values)]
        if max_tier is not None:
            self.report_args += ["--max-tier", str(max_tier)]
        if tags:
            self.report_args += ["--tags", ",".join(str(tag) for tag in tags)]
        if point is not None:
            self.report_args += ["--point", str(point)]

        result = subprocess.call(["npm", "ls"], cwd=web_path, stdout=subprocess.DEVNULL)
        if result != 0:
            raise RuntimeError(
                "Viewer not installed.\n"
                "If npm is installed: \n"
                "    You may need to run `npm install` in the viewer directory. \n"
                "If npm is not installed: \n"
                "    see https://docs.npmjs.com/downloading-and-installing-node-js-and-npm"
            )

    def write(self, readout: Readout | list[Readout]):
        if self.written:
            raise RuntimeError(
                "A new ReportWriter instance is required for each `write(...)`"
            )

        if not isinstance(readout, list):
            readout = [readout]

        with tempfile.TemporaryDirectory() as tmp:
            json_path = Path(tmp) / "cov.json"
            report_path = Path(tmp) / "report.html"
            json_writer = JSONWriter(json_path)
            for a_readout in readout:
                json_writer.write(a_readout)

            report_cmd = [
                "npm",
                "run",
                "report",
                "--",
                "--json",
                json_path.as_posix(),
                "--output",
                report_path.as_posix(),
                *self.report_args,
            ]
            result = subprocess.call(report_cmd, cwd=self.web_path)

            if result != 0:
                raise RuntimeError("Could not generate coverage report!")

            shutil.copy(report_path, self.output)
        self.written = True
