#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2023-2026 Noodle-Bytes. All Rights Reserved

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import List, Tuple


def parse_index(index_path: Path) -> List[Tuple[str, str]]:
    """
    Parse docs/index.md to extract an ordered list of (title, filename).
    Lines are expected in the form:

        1. [Title](file.md)
    """
    text = index_path.read_text(encoding="utf8")
    pattern = re.compile(r"^\s*\d+\.\s+\[(?P<title>.+?)\]\((?P<filename>.+?)\)")

    entries: List[Tuple[str, str]] = []
    for line in text.splitlines():
        match = pattern.match(line)
        if match:
            title = match.group("title").strip()
            filename = match.group("filename").strip()
            entries.append((title, filename))

    if not entries:
        raise SystemExit(f"No contents entries found in {index_path}")

    return entries


def build_nav_footer(
    prev_title: str,
    prev_filename: str,
    *,
    next_title: str | None = None,
    next_filename: str | None = None,
    is_last: bool = False,
) -> str:
    """
    Build the navigation footer block appended to each document.
    """
    lines = [
        "",
        "<!-- Navigation links below are auto-generated by "
        "tools/update_docs_nav.py. Do not edit manually. -->",
        "---",
        "<br>",
        "",
        f"Prev: [{prev_title}]({prev_filename})",
        "<br>",
    ]

    if is_last:
        lines.append("Back to index: [Index](index.md)")
    elif next_title and next_filename:
        lines.append(f"Next: [{next_title}]({next_filename})")

    return "\n" + "\n".join(lines) + "\n"


def update_doc(doc_path: Path, nav_footer: str) -> bool:
    """
    Replace any existing nav footer in doc_path with nav_footer.

    The nav footer is detected as the last occurrence of the marker:
        ---\n<br>
    and everything from that marker to EOF is replaced.
    """
    text = doc_path.read_text(encoding="utf8")

    # Prefer stripping from the auto-generated comment if present, so we
    # clean up any older versions of the footer (including older comments).
    comment_marker = "<!-- Navigation links below are auto-generated"
    marker = "---\n<br>"

    idx_comment = text.find(comment_marker)
    if idx_comment != -1:
        text = text[:idx_comment]
    else:
        idx = text.rfind(marker)
        if idx != -1:
            # Strip any existing footer from the marker to the end.
            text = text[:idx]

    text = text.rstrip()
    new_text = text + nav_footer

    if not new_text.endswith("\n"):
        new_text += "\n"

    if new_text != doc_path.read_text(encoding="utf8"):
        doc_path.write_text(new_text, encoding="utf8")
        return True

    return False


def main(argv: List[str] | None = None) -> int:
    argv = argv or sys.argv[1:]

    repo_root = Path(__file__).resolve().parents[1]
    docs_dir = repo_root / "docs"
    index_md = docs_dir / "index.md"

    if not index_md.is_file():
        print(f"index.md not found at {index_md}", file=sys.stderr)
        return 1

    entries = parse_index(index_md)

    changed_any = False

    for i, (title, filename) in enumerate(entries):
        doc_path = docs_dir / filename
        if not doc_path.is_file():
            print(
                f"warning: documentation file listed in index but missing: {filename}",
                file=sys.stderr,
            )
            continue

        if i == 0:
            # First doc: previous is the index, next is the second entry.
            prev_title, prev_filename = "Index", "index.md"
            next_title, next_filename = entries[i + 1]
            nav_footer = build_nav_footer(
                prev_title,
                prev_filename,
                next_title=next_title,
                next_filename=next_filename,
                is_last=False,
            )
        elif i == len(entries) - 1:
            # Last doc: previous is the penultimate; show "Back to index".
            prev_title, prev_filename = entries[i - 1]
            nav_footer = build_nav_footer(
                prev_title,
                prev_filename,
                is_last=True,
            )
        else:
            # Middle docs: previous and next are neighbors in the list.
            prev_title, prev_filename = entries[i - 1]
            next_title, next_filename = entries[i + 1]
            nav_footer = build_nav_footer(
                prev_title,
                prev_filename,
                next_title=next_title,
                next_filename=next_filename,
                is_last=False,
            )

        if update_doc(doc_path, nav_footer):
            changed_any = True

    if changed_any:
        print("Updated documentation navigation footers.")
    else:
        print("Documentation navigation footers already up to date.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
